language: python
script: ./scripts/build
install:
- sudo add-apt-repository ppa:texlive-backports/ppa -y
- sudo apt-get update
- sudo cp -r assets/fonts/* /usr/local/share/fonts/
- sudo fc-cache -f -v
- sudo apt-get install texlive-latex-recommended
- sudo apt-get install texlive-latex-extra
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-xetex
deploy:
  provider: s3
  access_key_id: AKIAILY5S7AZ77Q4BYBA
  secret_access_key:
    secure: "os6r0tpMbE6e9GBcQn2S/kAPpeQy61ddB5+5N5FGgYv6pm3wL53enTldr1ZAxCp08PXX71mbufGU30WM4lmq4EFT8+zpZhOild30X6ICg8FKaC5Ip99Cp5dB+A+lzxmkF7F1eegxMXgBhfNuNjtM3/97ffyvcCR5xwR2A9Aka4w="
  bucket: dissertate.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: suchow/Dissertate
    branch: master
notifications:
  email:
    recipients:
      - suchow@post.harvard.edu
    on_success: always
    on_failure: always
